[#ftl]
[@b.navbar brand="Beangle Config Browser"]
  [@b.nav class="navbar-nav"]
   [@b.navitem href="/config/mvc/index"]MVC[/@]
   [@b.navitem href="/config/container/index"]Beans[/@]
   [@b.navitem href="/config/hibernate/index"]Hibernate[/@]
   [@b.navitem href="/config/freemarker/index"]Freemarker[/@]
   [@b.navitem href="/config/dependency/index"]Jars[/@]
   [@b.navitem href="/config/webinit/index"]Web.xml[/@]
  [/@]
[/@]
