[#ftl]
[@b.navbar brand="Beangle Config Browser"]
  [@b.nav class="navbar-nav"]
   [@b.navitem href="/inspect/mvc/index"]MVC[/@]
   [@b.navitem href="/inspect/container/index"]Beans[/@]
   [@b.navitem href="/inspect/hibernate/index"]Hibernate[/@]
   [@b.navitem href="/inspect/freemarker/index"]Freemarker[/@]
   [@b.navitem href="/inspect/dependency/index"]Jars[/@]
   [@b.navitem href="/inspect/webinit/index"]Web.xml[/@]
  [/@]
[/@]
