[#ftl]
[@b.navbar brand="Beangle Configuration Browser"]
  [@b.navlist]
   [@b.navitem href="/config/mvc"]MVC[/@]
   [@b.navitem href="/config/container/index"]Beans[/@]
   [@b.navitem href="/config/freemarker/index"]Freemarker[/@]
   [@b.navitem href="/config/dependency/index"]Jars[/@]
   [@b.navitem href="/config/webinit/index"]Web.xml[/@]
  [/@]
[/@]
